import { useArgus } from "@/data/api";
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Card, PageHeader, FilterBar, Select, Input, TableWrapper, Th, Td, SeverityBadge, StatusBadge, Button } from "@/components/ui";
import { severityColor } from "@/data/mockData";

export default function Threats() {
  const { ALERTS, data, connected, updateAlert, mutate, busy } = useArgus();
  const navigate = useNavigate();
  const [severityFilter, setSeverityFilter] = useState("All");
  const [statusFilter, setStatusFilter] = useState("All");
  const [classFilter, setClassFilter] = useState("All");
  const [search, setSearch] = useState("");

  const counts = {
    total: ALERTS.length,
    critical: ALERTS.filter((a) => a.severity === "critical").length,
    high: ALERTS.filter((a) => a.severity === "high").length,
    medium: ALERTS.filter((a) => a.severity === "medium").length,
    low: ALERTS.filter((a) => a.severity === "low").length,
  };

  const classes = ["All", ...Array.from(new Set(ALERTS.map((a) => a.threat_class)))];

  const filtered = ALERTS.filter((a) => {
    if (severityFilter !== "All" && a.severity !== severityFilter.toLowerCase()) return false;
    if (statusFilter !== "All" && a.status !== statusFilter) return false;
    if (classFilter !== "All" && a.threat_class !== classFilter) return false;
    if (search && !a.alert_id.includes(search) && !a.threat_class.toLowerCase().includes(search.toLowerCase()) && !a.source.ip.includes(search)) return false;
    return true;
  });

  return (
    <div className="p-6 max-w-[1440px] mx-auto space-y-4">
      <PageHeader
        title="Threats"
        breadcrumb="Detection"
        subtitle="Detected security events generated by ARGUS-ONE detection engines."
      />

      {/* Stats */}
      <div className="grid grid-cols-5 gap-3">
        {[
          { label: "Total", val: counts.total, color: "#F3F5F7" },
          { label: "Critical", val: counts.critical, color: "#EB5757" },
          { label: "High", val: counts.high, color: "#F2994A" },
          { label: "Medium", val: counts.medium, color: "#F2C94C" },
          { label: "Low", val: counts.low, color: "#4C9AFF" },
        ].map((s) => (
          <Card key={s.label} className="p-3 flex justify-between items-center cursor-pointer hover:border-[#3A4456] transition-colors" onClick={() => setSeverityFilter(s.label === "Total" ? "All" : s.label)} >
            <span className="text-[11px] text-[#66707D] uppercase tracking-wide">{s.label}</span>
            <span className="text-[22px] font-bold font-mono" style={{ color: s.color }}>{s.val}</span>
          </Card>
        ))}
      </div>

      {/* Filters */}
      <FilterBar>
        <Input value={search} onChange={setSearch} placeholder="Alert ID, source IP, threat class..." className="w-64" />
        <Select value={severityFilter} onChange={setSeverityFilter}>
          <option value="All">All Severities</option>
          <option value="Critical">Critical</option>
          <option value="High">High</option>
          <option value="Medium">Medium</option>
          <option value="Low">Low</option>
        </Select>
        <Select value={classFilter} onChange={setClassFilter}>
          {classes.map((c) => <option key={c}>{c}</option>)}
        </Select>
        <Select value={statusFilter} onChange={setStatusFilter}>
          <option value="All">All Statuses</option>
          <option value="OPEN">Open</option>
          <option value="ACKNOWLEDGED">Acknowledged</option>
          <option value="RESOLVED">Resolved</option>
        </Select>
        <Button variant="ghost" size="sm">Detector ▾</Button>
        <Button variant="ghost" size="sm">Time Range ▾</Button>
        <span className="ml-auto text-[11px] text-[#66707D]">{filtered.length} threats</span>
      </FilterBar>

      {/* Table */}
      <Card>
        <TableWrapper>
          <thead>
            <tr>
              <Th>Alert ID</Th>
              <Th>Timestamp</Th>
              <Th>Threat Class</Th>
              <Th>Severity</Th>
              <Th>Risk</Th>
              <Th>Source</Th>
              <Th>Target</Th>
              <Th>Detector</Th>
              <Th>Window</Th>
              <Th>Status</Th>
            </tr>
          </thead>
          <tbody>
            {filtered.map((a) => (
              <tr
                key={a.alert_id}
                className="hoverable cursor-pointer"
                onClick={() => navigate(`/alerts/${a.alert_id}`)}
              >
                <Td mono className="text-[#20D3A2]">{a.alert_id}</Td>
                <Td mono>{a.timestamp.replace("T", " ").replace("Z", " UTC")}</Td>
                <Td className="text-[#F3F5F7] font-medium">{a.threat_class}</Td>
                <Td><SeverityBadge severity={a.severity} /></Td>
                <Td>
                  <span className="font-mono font-bold text-[13px]" style={{ color: severityColor(a.severity) }}>
                    {Math.round(a.risk_score * 100)}
                  </span>
                </Td>
                <Td mono>{a.source.ip}</Td>
                <Td mono>{a.target.ip}</Td>
                <Td mono className="text-[#66707D]">{a.detector}</Td>
                <Td mono>{a.window_seconds > 0 ? `${a.window_seconds}s` : "—"}</Td>
                <Td><StatusBadge status={a.status} /></Td>
              </tr>
            ))}
          </tbody>
        </TableWrapper>
      </Card>
    </div>
  );
}
